【用途】EC2インスタンスの作成
※ImageIdはEC2で使用されているamiのImageIdに変更すること
※EC2のスペックを選択できるようにパラメーターが追加されている

---------------------------------------------

AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0792756bc9edf3e63
      InstanceType: !Ref InstanceType
      Tags:
      - Key: Name
        Value: myInstance
---------------------------------------------
