【用途】EC2インスタンスの作成
※ImageIdはEC2で使用されているamiのImageIdに変更すること
※下記項目が選択可能になる
・EC2インスタンスのスペック
・amiイメージを2つのリージョン（東京とシンガポール）から選択可能（各リージョンにamiイメージの配置が必要）
---------------------------------------------


AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance
Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type
Mappings: 
  RegionMap: 
    ap-northeast-1:
      hvm: "ami-0792756bc9edf3e63"
    ap-southeast-1:
      hvm: "ami-0162da29310cc18f6"

Description: Create EC2 Instance
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', hvm]
      InstanceType: !Ref InstanceType
      Tags:
      - Key: Name
        Value: myInstance
---------------------------------------------
