Parameters:
  Ec2InstanceType:
    Description: EC2 InstanceType
    Type: String
    Default: t3.small
  Ec2ImageId:
    Description: EC2 ImageID(AMI)
    Type: String 
    Default: ami-08d701f46d96fddb2 #Windows_Server-2019-Japanese-Full-Base-2025.11.12
  SystemName:
    Type: String
    Default: udemy

Resources:
 ##EC2 IMDSv2
  IMDSv2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
        LaunchTemplateName: !Sub ${SystemName}-memsv-IMDSV2
        LaunchTemplateData:
          MetadataOptions:
            HttpEndpoint: enabled
            HttpPutResponseHopLimit: 1
            HttpTokens: required

  Ec2Instance01:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            c:\cfn\cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
            c:\cfn\hooks.d\cfn-auto-reloader.conf:
              content: !Sub |
                 [cfn-auto-reloader-hook]
                 triggers=post.update
                 path=Resources.Ec2Instance01.Metadata.AWS::CloudFormation::Init
                 action=cfn-init.exe -v --stack ${AWS::StackName} --resource Ec2Instance01 --region ${AWS::Region}
            c:\cfn\scripts\Setup-config1.ps1:
              content: |
                 Add-Type -Assembly System.Windows.Forms
                 [System.Windows.Forms.MessageBox]::Show("Setup is in progress. Please wait until setup is complete.", "Please wait","OK","Warning")
            c:\cfn\scripts\Setup-config2.ps1:
              content: |
                 $log = "c:\cfn\scripts\Cfnlog.txt"
                 echo Setup-config2-Start >> $log        
                 New-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "Setting" -PropertyType "String" -Value "powershell -file c:\cfn\scripts\Setup-config1.ps1  -WindowStyle Hidden"
                 tzutil /s "Tokyo Standard Time" >> $log 
                 Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\TimeZoneInformation" -Name "RealTimeIsUniversal" -Value 1

                 #Key Layout
                 [string]$Path = "HKLM:\SYSTEM\CurrentControlSet\services\i8042prt\Parameters"
                 Set-ItemProperty -Path $Path -Name "LayerDriver JPN" -Value "kbd106.dll"
                 Set-ItemProperty -Path $Path -Name "OverrideKeyboardIdentifier" -Value "PCAT_106KEY"
                 Set-ItemProperty -Path $Path -Name "OverrideKeyboardType" -Value 7
                 Set-ItemProperty -Path $Path -Name "OverrideKeyboardSubtype" -Value 2

                 Get-NetFirewallProfile | Set-NetFirewallProfile -Enabled false >> $log
                 net user administrator Moscow3#
                 Rename-Computer -NewName SV01 -Force -Restart 
                 echo Setup-config2-End >> $log
            c:\cfn\scripts\Setup-config3.ps1:
              content: |
                 if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Administrators")) { Start-Process powershell.exe "-File `"$PSCommandPath`"" -Verb RunAs; exit }
                 $log = "c:\cfn\scripts\Cfnlog.txt"
                 echo Setup-config3-Start >> $log                 
                 Set-DnsClientServerAddress -InterfaceAlias * -ServerAddress "192.168.1.20" >> $log  
                 
                 $User = "corp\administrator"
                 $PWord = ConvertTo-SecureString -String "Moscow3#" -AsPlainText -Force
                 $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
                 Add-Computer -DomainName "corp.local" -Credential $Credential -Force -Restart
                 echo Setup-config3-End >> $log
            c:\cfn\scripts\Setup-config4.ps1:
              content: |
                 Add-Type -Assembly System.Windows.Forms
                 [System.Windows.Forms.MessageBox]::Show("Setup is complete.Let's get started.", "Setup is complete.","OK","Information")
            c:\cfn\scripts\Setup-config5.ps1:
              content: |
                 if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Administrators")) { Start-Process powershell.exe "-File `"$PSCommandPath`"" -Verb RunAs; exit }
                 $log = "c:\cfn\scripts\Cfnlog.txt"
                 echo Setup-config5-Start >> $log 

                 #Password Expires False
                 wmic UserAccount where Name='administrator' set PasswordExpires=False

                 #IE ESC Administrators Off
                 Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}' -Name "IsInstalled" -Value 0

                 Remove-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "Setting"
                 New-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce" -Name "Setting" -PropertyType "String" -Value "powershell -file c:\cfn\scripts\Setup-config4.ps1 -WindowStyle Hidden"
                 echo Setup-config5-End >> $log
          commands:
            2-setup-config:
              command: 'powershell.exe -File c:\cfn\scripts\Setup-config2.ps1'
              waitAfterCompletion: forever
            3-setup-config:
              command: 'powershell.exe -File c:\cfn\scripts\Setup-config3.ps1'
              waitAfterCompletion: forever
            5-setup-config:
              command: 'powershell.exe -File c:\cfn\scripts\Setup-config5.ps1'
              waitAfterCompletion: '0'
          services:
            windows:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - c:\cfn\cfn-hup.conf
                  - c:\cfn\hooks.d\cfn-auto-reloader.conf     
    Properties:
      InstanceType: !Ref Ec2InstanceType
      ImageId: !Ref Ec2ImageId
      LaunchTemplate: 
        LaunchTemplateName: !Sub ${SystemName}-IMDSV2
        Version: 1
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - Fn::ImportValue:
                !Sub '${SystemName}-SVSecuritygroupID'
          SubnetId: 
            Fn::ImportValue:
              !Sub '${SystemName}-PublicSubnetID'
          PrivateIpAddress: 192.168.1.31
      IamInstanceProfile: 
        Fn::ImportValue: 
          !Sub '${SystemName}-InstanceProfileID'
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-sv01
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          cfn-init.exe -v --stack ${AWS::StackName} --resource Ec2Instance01 --region ${AWS::Region}
          cfn-signal.exe -e $lastexitcode --stack ${AWS::StackName} --resource Ec2Instance01 --region ${AWS::Region}
          </powershell>
    DependsOn: IMDSv2LaunchTemplate


  Ec2Instance02:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            c:\cfn\cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
            c:\cfn\hooks.d\cfn-auto-reloader.conf:
              content: !Sub |
                 [cfn-auto-reloader-hook]
                 triggers=post.update
                 path=Resources.Ec2Instance02.Metadata.AWS::CloudFormation::Init
                 action=cfn-init.exe -v --stack ${AWS::StackName} --resource Ec2Instance02 --region ${AWS::Region}
            c:\cfn\scripts\Setup-config1.ps1:
              content: |
                 Add-Type -Assembly System.Windows.Forms
                 [System.Windows.Forms.MessageBox]::Show("Setup is in progress. Please wait until setup is complete.", "Please wait","OK","Warning")
            c:\cfn\scripts\Setup-config2.ps1:
              content: |
                 $log = "c:\cfn\scripts\Cfnlog.txt"
                 echo Setup-config2-Start >> $log        
                 New-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "Setting" -PropertyType "String" -Value "powershell -file c:\cfn\scripts\Setup-config1.ps1  -WindowStyle Hidden"
                 tzutil /s "Tokyo Standard Time" >> $log 
                 Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\TimeZoneInformation" -Name "RealTimeIsUniversal" -Value 1

                 #Key Layout
                 [string]$Path = "HKLM:\SYSTEM\CurrentControlSet\services\i8042prt\Parameters"
                 Set-ItemProperty -Path $Path -Name "LayerDriver JPN" -Value "kbd106.dll"
                 Set-ItemProperty -Path $Path -Name "OverrideKeyboardIdentifier" -Value "PCAT_106KEY"
                 Set-ItemProperty -Path $Path -Name "OverrideKeyboardType" -Value 7
                 Set-ItemProperty -Path $Path -Name "OverrideKeyboardSubtype" -Value 2

                 Get-NetFirewallProfile | Set-NetFirewallProfile -Enabled false >> $log
                 net user administrator Moscow3#
                 Rename-Computer -NewName SV02 -Force -Restart 
                 echo Setup-config2-End >> $log
            c:\cfn\scripts\Setup-config3.ps1:
              content: |
                 if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Administrators")) { Start-Process powershell.exe "-File `"$PSCommandPath`"" -Verb RunAs; exit }
                 $log = "c:\cfn\scripts\Cfnlog.txt"
                 echo Setup-config3-Start >> $log                 
                 Set-DnsClientServerAddress -InterfaceAlias * -ServerAddress "192.168.1.20" >> $log  
                 
                 $User = "corp\administrator"
                 $PWord = ConvertTo-SecureString -String "Moscow3#" -AsPlainText -Force
                 $Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
                 Add-Computer -DomainName "corp.local" -Credential $Credential -Force -Restart
                 echo Setup-config3-End >> $log
            c:\cfn\scripts\Setup-config4.ps1:
              content: |
                 Add-Type -Assembly System.Windows.Forms
                 [System.Windows.Forms.MessageBox]::Show("Setup is complete.Let's get started.", "Setup is complete.","OK","Information")
            c:\cfn\scripts\Setup-config5.ps1:
              content: |
                 if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("Administrators")) { Start-Process powershell.exe "-File `"$PSCommandPath`"" -Verb RunAs; exit }
                 $log = "c:\cfn\scripts\Cfnlog.txt"
                 echo Setup-config5-Start >> $log 

                 #Password Expires False
                 wmic UserAccount where Name='administrator' set PasswordExpires=False

                 #IE ESC Administrators Off
                 Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Active Setup\Installed Components\{A509B1A7-37EF-4b3f-8CFC-4F3A74704073}' -Name "IsInstalled" -Value 0

                 Remove-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "Setting"
                 New-ItemProperty -Path "HKLM:\Software\Microsoft\Windows\CurrentVersion\RunOnce" -Name "Setting" -PropertyType "String" -Value "powershell -file c:\cfn\scripts\Setup-config4.ps1 -WindowStyle Hidden"
                 echo Setup-config5-End >> $log
          commands:
            2-setup-config:
              command: 'powershell.exe -File c:\cfn\scripts\Setup-config2.ps1'
              waitAfterCompletion: forever
            3-setup-config:
              command: 'powershell.exe -File c:\cfn\scripts\Setup-config3.ps1'
              waitAfterCompletion: forever
            5-setup-config:
              command: 'powershell.exe -File c:\cfn\scripts\Setup-config5.ps1'
              waitAfterCompletion: '0'
          services:
            windows:
              cfn-hup:
                enabled: 'true'
                ensureRunning: 'true'
                files:
                  - c:\cfn\cfn-hup.conf
                  - c:\cfn\hooks.d\cfn-auto-reloader.conf     
    Properties:
      InstanceType: !Ref Ec2InstanceType
      ImageId: !Ref Ec2ImageId
      LaunchTemplate: 
        LaunchTemplateName: !Sub ${SystemName}-IMDSV2
        Version: 1
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - Fn::ImportValue:
                !Sub '${SystemName}-SVSecuritygroupID'
          SubnetId: 
            Fn::ImportValue:
              !Sub '${SystemName}-PublicSubnetID'
          PrivateIpAddress: 192.168.1.32
      IamInstanceProfile: 
        Fn::ImportValue: 
          !Sub '${SystemName}-InstanceProfileID'
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-sv02
      UserData:
        Fn::Base64: !Sub |
          <powershell>
          cfn-init.exe -v --stack ${AWS::StackName} --resource Ec2Instance02 --region ${AWS::Region}
          cfn-signal.exe -e $lastexitcode --stack ${AWS::StackName} --resource Ec2Instance02 --region ${AWS::Region}
          </powershell>
    DependsOn: IMDSv2LaunchTemplate